CREATE OR REPLACE VIEW `{{ params.project_id }}.crispy_dwh.tabla_resumen`
AS 
SELECT
  A.PROBABILITY
  ,SUM(CASE WHEN A.TARGET = 1 THEN A.DATES ELSE 0 END) AS TGT_1
  ,SUM(CASE WHEN A.TARGET = 0 THEN A.DATES ELSE 0 END) AS TGT_0
  ,ROUND(100 * SUM(CASE WHEN A.TARGET = 1 THEN A.DATES ELSE 0 END)/ SUM (A.DATES),2) AS PTGT_1
  ,ROUND(100 * SUM(CASE WHEN A.TARGET = 0 THEN A.DATES ELSE 0 END)/ SUM (A.DATES),2) AS PTGT_0
FROM
  (
SELECT
  FLOOR((predict*100)/10)*10 AS PROBABILITY
  ,tgt AS TARGET
  ,COUNT(*) AS DATES
FROM
  `{{ params.project_id }}.crispy_dwh.predictions`
GROUP BY
  FLOOR ((predict*100)/10)*10
  ,tgt
) AS A
GROUP BY
  A.PROBABILITY
ORDER BY
  A.PROBABILITY


